# Complete reference: https://docs.coderabbit.ai/reference/configuration

# Language for the review
language: 'en-US'

reviews:
  profile: 'chill'
  ignored_branches:
    - 'none'
  # Automatically review pull requests
  auto_review:
    enabled: true
    # Do not review draft PRs
    drafts: false
  # Exclude certain files from review
  path_filters:
    - '!**/pnpm-lock.yaml'
    - '!**/bun.lock'
    - '!**/LICENSE'
    - '!**/.gitignore'
    - '!**/example.env'
    - '!**/.env.example'
    - '!**/.agents'

  # Generate a high-level summary of the changes in the PR description.
  high_level_summary: true

  # Path-specific review instructions.
  file_path_instructions:
    - path: '**/*' # General instructions for all files
      instructions: |
        Please review the following changes for correctness, clarity, and adherence to project conventions.
        - **Context**: This is "Tijori", a secure environment variables manager. We are pivoting from Next.js/Supabase to **TanStack Start + Convex**.
        - Check for any breaking changes.
        - Ensure that the code is well-documented.
        - Verify that the changes are consistent with the existing coding style (Tailwind CSS v4, TypeScript).
        - Cross-check with `@init.md` for architectural alignment.
        - Every new change (in the form of PR) should bump the version in package.json.

    - path: 'convex/**/*.{ts,tsx}'
      instructions: |
        These are Convex backend functions and schema definitions.
        - Verify `v.*` validators are strict and appropriate for all input arguments.
        - **Performance**: Ensure indices are defined and used for all queries. Avoid using `.collect()` on potentially large result sets; prefer pagination or narrow filters.
        - **Security**: Ensure authentication checks (e.g., `getUser`) and project/environment access checks are robustly implemented in every mutation and sensitive query.
        - **Security**: The server should NEVER see plain text secrets. Only encrypted payloads and hashes should reach the database.
        - **Consistency**: Centralized error handling using `throwError` and centralized validation with `validateLength` using constants from `src/lib/constants.ts`.

    - path: 'src/utils/crypto.ts'
      instructions: |
        CRITICAL: Client-side cryptography logic.
        - Verify AES-256-GCM implementation.
        - Verify PBKDF2 key derivation settings (iterations > 100,000, correct salt usage).
        - Ensure no secrets are logged or exposed.

    - path: '**/*.md'
      instructions: |
        Documentation changes (including `init.md`, `learning.md`).
        - Check for clarity and accuracy.
        - Ensure `init.md` reflects the current progress and architectural decisions.
        - Check grammar and formatting.

    - path: 'src/{components,routes}/**/*.{tsx,ts}'
      instructions: |
        These are changes to UI components and routes. Please check for:
        - Correct rendering, functionality, and proper use of semantic HTML.
        - Adherence to the design system (Tailwind CSS v4, Dark Mode, glassmorphism, gradients, and micro-animations).
        - Responsiveness and accessibility (ARIA labels, keyboard navigation).
        - **Data Fetching**: Ensure `useQuery` and `useMutation` from `convex/react` are used correctly with optimal dependency arrays where needed.
        - **Mutation Best Practices**:
            - Always handle loading states (e.g., `isLoading` spinner, disabled buttons).
            - Always handle error states with user-facing feedback (e.g., `toast.error`, error alerts).
            - Implement optimistic updates for critical UI paths to ensure a premium, lag-free experience.
            - Guard against race conditions and double-submissions (debouncing, state-based disabling).
        - **Security**: Ensure master keys and passcodes are never exposed in logs, component props, or unencrypted state. Use the `keyStore` and React Context for secure key management.

    - path: 'package.json'
      instructions: |
        Dependency changes detected. Please verify:
        - The necessity of any new dependencies (Prefer minimal dependencies).
        - Potential for conflicts or security vulnerabilities.
        - That the changes are reflected in the lock file (`bun.lock`).
        - For every new change (in the form of PR) should bump the version in package.json.
