/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DRouteImport } from './routes/d'
import { Route as CryptoTestRouteImport } from './routes/crypto-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ShareShareIdRouteImport } from './routes/share/$shareId'
import { Route as DocsSecurityRouteImport } from './routes/docs/security'
import { Route as DocsLocalSetupRouteImport } from './routes/docs/local-setup'
import { Route as DocsDeploymentRouteImport } from './routes/docs/deployment'
import { Route as DSharedRouteImport } from './routes/d/shared'
import { Route as DSettingsRouteImport } from './routes/d/settings'
import { Route as DProfileRouteImport } from './routes/d/profile'
import { Route as DDashboardRouteImport } from './routes/d/dashboard'
import { Route as DAdminRouteImport } from './routes/d/admin'
import { Route as DProjectsIndexRouteImport } from './routes/d/projects/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DProjectsNewRouteImport } from './routes/d/projects/new'
import { Route as DProjectProjectIdRouteImport } from './routes/d/project/$projectId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DRoute = DRouteImport.update({
  id: '/d',
  path: '/d',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoTestRoute = CryptoTestRouteImport.update({
  id: '/crypto-test',
  path: '/crypto-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLocalSetupRoute = DocsLocalSetupRouteImport.update({
  id: '/local-setup',
  path: '/local-setup',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDeploymentRoute = DocsDeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => DocsRoute,
} as any)
const DSharedRoute = DSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => DRoute,
} as any)
const DSettingsRoute = DSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DRoute,
} as any)
const DProfileRoute = DProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DRoute,
} as any)
const DDashboardRoute = DDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DRoute,
} as any)
const DAdminRoute = DAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DRoute,
} as any)
const DProjectsIndexRoute = DProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DProjectsNewRoute = DProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => DRoute,
} as any)
const DProjectProjectIdRoute = DProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => DRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crypto-test': typeof CryptoTestRoute
  '/d': typeof DRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/d/admin': typeof DAdminRoute
  '/d/dashboard': typeof DDashboardRoute
  '/d/profile': typeof DProfileRoute
  '/d/settings': typeof DSettingsRoute
  '/d/shared': typeof DSharedRoute
  '/docs/deployment': typeof DocsDeploymentRoute
  '/docs/local-setup': typeof DocsLocalSetupRoute
  '/docs/security': typeof DocsSecurityRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/docs/': typeof DocsIndexRoute
  '/d/project/$projectId': typeof DProjectProjectIdRoute
  '/d/projects/new': typeof DProjectsNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/d/projects': typeof DProjectsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crypto-test': typeof CryptoTestRoute
  '/d': typeof DRouteWithChildren
  '/d/admin': typeof DAdminRoute
  '/d/dashboard': typeof DDashboardRoute
  '/d/profile': typeof DProfileRoute
  '/d/settings': typeof DSettingsRoute
  '/d/shared': typeof DSharedRoute
  '/docs/deployment': typeof DocsDeploymentRoute
  '/docs/local-setup': typeof DocsLocalSetupRoute
  '/docs/security': typeof DocsSecurityRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/docs': typeof DocsIndexRoute
  '/d/project/$projectId': typeof DProjectProjectIdRoute
  '/d/projects/new': typeof DProjectsNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/d/projects': typeof DProjectsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crypto-test': typeof CryptoTestRoute
  '/d': typeof DRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/d/admin': typeof DAdminRoute
  '/d/dashboard': typeof DDashboardRoute
  '/d/profile': typeof DProfileRoute
  '/d/settings': typeof DSettingsRoute
  '/d/shared': typeof DSharedRoute
  '/docs/deployment': typeof DocsDeploymentRoute
  '/docs/local-setup': typeof DocsLocalSetupRoute
  '/docs/security': typeof DocsSecurityRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/docs/': typeof DocsIndexRoute
  '/d/project/$projectId': typeof DProjectProjectIdRoute
  '/d/projects/new': typeof DProjectsNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/d/projects/': typeof DProjectsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crypto-test'
    | '/d'
    | '/docs'
    | '/d/admin'
    | '/d/dashboard'
    | '/d/profile'
    | '/d/settings'
    | '/d/shared'
    | '/docs/deployment'
    | '/docs/local-setup'
    | '/docs/security'
    | '/share/$shareId'
    | '/docs/'
    | '/d/project/$projectId'
    | '/d/projects/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/d/projects'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crypto-test'
    | '/d'
    | '/d/admin'
    | '/d/dashboard'
    | '/d/profile'
    | '/d/settings'
    | '/d/shared'
    | '/docs/deployment'
    | '/docs/local-setup'
    | '/docs/security'
    | '/share/$shareId'
    | '/docs'
    | '/d/project/$projectId'
    | '/d/projects/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/d/projects'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/crypto-test'
    | '/d'
    | '/docs'
    | '/d/admin'
    | '/d/dashboard'
    | '/d/profile'
    | '/d/settings'
    | '/d/shared'
    | '/docs/deployment'
    | '/docs/local-setup'
    | '/docs/security'
    | '/share/$shareId'
    | '/docs/'
    | '/d/project/$projectId'
    | '/d/projects/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/d/projects/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CryptoTestRoute: typeof CryptoTestRoute
  DRoute: typeof DRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ShareShareIdRoute: typeof ShareShareIdRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d': {
      id: '/d'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof DRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto-test': {
      id: '/crypto-test'
      path: '/crypto-test'
      fullPath: '/crypto-test'
      preLoaderRoute: typeof CryptoTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/local-setup': {
      id: '/docs/local-setup'
      path: '/local-setup'
      fullPath: '/docs/local-setup'
      preLoaderRoute: typeof DocsLocalSetupRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/deployment': {
      id: '/docs/deployment'
      path: '/deployment'
      fullPath: '/docs/deployment'
      preLoaderRoute: typeof DocsDeploymentRouteImport
      parentRoute: typeof DocsRoute
    }
    '/d/shared': {
      id: '/d/shared'
      path: '/shared'
      fullPath: '/d/shared'
      preLoaderRoute: typeof DSharedRouteImport
      parentRoute: typeof DRoute
    }
    '/d/settings': {
      id: '/d/settings'
      path: '/settings'
      fullPath: '/d/settings'
      preLoaderRoute: typeof DSettingsRouteImport
      parentRoute: typeof DRoute
    }
    '/d/profile': {
      id: '/d/profile'
      path: '/profile'
      fullPath: '/d/profile'
      preLoaderRoute: typeof DProfileRouteImport
      parentRoute: typeof DRoute
    }
    '/d/dashboard': {
      id: '/d/dashboard'
      path: '/dashboard'
      fullPath: '/d/dashboard'
      preLoaderRoute: typeof DDashboardRouteImport
      parentRoute: typeof DRoute
    }
    '/d/admin': {
      id: '/d/admin'
      path: '/admin'
      fullPath: '/d/admin'
      preLoaderRoute: typeof DAdminRouteImport
      parentRoute: typeof DRoute
    }
    '/d/projects/': {
      id: '/d/projects/'
      path: '/projects'
      fullPath: '/d/projects'
      preLoaderRoute: typeof DProjectsIndexRouteImport
      parentRoute: typeof DRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/projects/new': {
      id: '/d/projects/new'
      path: '/projects/new'
      fullPath: '/d/projects/new'
      preLoaderRoute: typeof DProjectsNewRouteImport
      parentRoute: typeof DRoute
    }
    '/d/project/$projectId': {
      id: '/d/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/d/project/$projectId'
      preLoaderRoute: typeof DProjectProjectIdRouteImport
      parentRoute: typeof DRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DRouteChildren {
  DAdminRoute: typeof DAdminRoute
  DDashboardRoute: typeof DDashboardRoute
  DProfileRoute: typeof DProfileRoute
  DSettingsRoute: typeof DSettingsRoute
  DSharedRoute: typeof DSharedRoute
  DProjectProjectIdRoute: typeof DProjectProjectIdRoute
  DProjectsNewRoute: typeof DProjectsNewRoute
  DProjectsIndexRoute: typeof DProjectsIndexRoute
}

const DRouteChildren: DRouteChildren = {
  DAdminRoute: DAdminRoute,
  DDashboardRoute: DDashboardRoute,
  DProfileRoute: DProfileRoute,
  DSettingsRoute: DSettingsRoute,
  DSharedRoute: DSharedRoute,
  DProjectProjectIdRoute: DProjectProjectIdRoute,
  DProjectsNewRoute: DProjectsNewRoute,
  DProjectsIndexRoute: DProjectsIndexRoute,
}

const DRouteWithChildren = DRoute._addFileChildren(DRouteChildren)

interface DocsRouteChildren {
  DocsDeploymentRoute: typeof DocsDeploymentRoute
  DocsLocalSetupRoute: typeof DocsLocalSetupRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDeploymentRoute: DocsDeploymentRoute,
  DocsLocalSetupRoute: DocsLocalSetupRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CryptoTestRoute: CryptoTestRoute,
  DRoute: DRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ShareShareIdRoute: ShareShareIdRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
